# package metadata

[project]
name = "marvin"
version = "0.5.0"
dynamic= ["dependencies", "optional-dependencies"]
description = "A batteries-included library for deploying custom AI tools."
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = ["ai", "chatbot", "llm"]
requires-python = ">=3.10"

[tools.setuptools.dynamic]
dependencies = {file = ["requirements.txt", "requirements-loaders.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ["requirements-dev.txt"]}

[project.urls]
Homepage = "https://github.com/prefecthq/marvin"

[project.scripts]
marvin = "marvin.cli.cli:app"

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


# pytest configuration
[tool.pytest.ini_options]
markers = ["llm: indicates that a test calls an LLM (may be slow)."]
norecursedirs = [
    "*.egg-info",
    ".git",
    ".mypy_cache",
    "node_modules",
    ".pytest_cache .vscode"
]
asyncio_mode = 'auto'
filterwarnings = [
    "ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning"
]
env = [
    "MARVIN_TEST_MODE=1",
    "D:MARVIN_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////tmp/test.sqlite",
    "MARVIN_LOG_CONSOLE_WIDTH=120",
    "MARVIN_LOG_LEVEL=DEBUG",
    # disable auto profile picture creation
    'MARVIN_BOT_CREATE_PROFILE_PICTURE=false',
    'MARVIN_OPENAI_MODEL_TEMPERATURE=0'
]

# black configuration
[tool.black]
preview = true

# ruff configuration
[tool.ruff]
extend-select = ["I"]

[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F401', 'E402']
"conftest.py" = ["F401", "F403"]
'tests/fixtures/*.py' = ['F403']
