name: Publish Docs

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies for social cards
        run: |
          apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      # for now, only install mkdocs. In the future may need to install Marvin itself.
      - name: Install dependencies for MKDocs Material
        run: pip install \
          mkdocs-material \
          mkdocs-autolinks-plugin \
          mkdocs-awesome-pages-plugin \
          mkdocstrings[python]
      - name: Publish docs
        run: mkdocs gh-deploy --force
